## Box Example Configuration ##
# Each box is defined in a file with name 'boxname.toml'
# Box names are assumed from the filename

identifier = 1                          # Host number for the box IP

# SSH check
[ssh]
port = 22                               # Port to check, default 22
auth = ['plaintext', 'pubkey']          # Authentication methods, currently only supporting [plaintext, pubkey], default plaintext
keyfile = ''                            # Private key file path to test pubkey, empty string if not using pubkey
credlist = []                           # Credlist to use for authentication

# http check
[http]
port = 80                               # Port to check, default 80
path = ''                               # Path to check, defaults to site root

# https check
[https]
port = 443                              # Port to check, default 443
path = ''                               # Path to check, defaults to site root