## Inject Example Configuration ##

name = 'Example Inject'                                             # Name of the inject
number = 1                                                          # Inject number
description = '''I guess this is a description'''                   # A description of the inject
worth = 100                                                         # Total possible points
path = ''                                                           # Path to supplemental info, optional (put '' if none)

# The rubric for inject scoring is defined here
# Each new grading category should be written [rubric.<category name>]
# The names of possible scores can then be defined with a description within [rubric.<category name>.categories]

# To visualize, it is equivalent to this:
# ======================================
# =| professionalism |    accuracy    |=
# ======================================
# =| fail | worth 0  | fail | worth 0 |=
# =| pass | worth 1  | pass | worth 1 |=

[[rubric]]

[rubric.professionalism]
weight = 0.3                                                        # Category weight, total should add up to 1
description = '''Submission should be professional'''               # Description of the category

[rubric.professionalism.categories]
troll = '''Didn't submit anything'''                                # name of the score = description of the name
dreadful = '''Minimum effort'''
poor = '''They tried'''
acceptable = '''Good enough'''
exceeds = '''Very profesh'''
outstanding = '''The most professional thing i've ever read'''

[rubric.accuracy]
weight = 0.7
description = '''Submission should have accurate information'''

[rubric.accuracy.categories]
fail = '''Not at all accurate'''
pass = '''Accurate information'''